#!/usr/bin/env python3
"""
JANASANKHYA — interactive HTML dashboard
========================================

Builds a single self-contained dashboard/janasankhya.html (all figures embedded
as base64, no external files needed) that walks through the whole built system:
thesis -> architecture -> CTGAN validation -> structural inequality ->
sample synthetic workers -> the AI-audit finding -> provenance.

Open it in any browser. Run after the pipeline.
"""

from __future__ import annotations

import os
import json
import base64
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULTS = os.path.join(ROOT, "results")
FIG = os.path.join(RESULTS, "figures")
OUT = os.path.join(ROOT, "dashboard", "janasankhya.html")


def img(name: str) -> str:
    p = os.path.join(FIG, name)
    if not os.path.exists(p):
        return "<p style='color:#999'>[figure not generated yet]</p>"
    b64 = base64.b64encode(open(p, "rb").read()).decode()
    return f"<img src='data:image/png;base64,{b64}' style='width:100%;max-width:980px;border:1px solid #ddd;border-radius:8px'/>"


def jload(name):
    p = os.path.join(RESULTS, name)
    return json.load(open(p)) if os.path.exists(p) else None


def metric(label, value, sub=""):
    return (f"<div class='metric'><div class='mv'>{value}</div>"
            f"<div class='ml'>{label}</div><div class='ms'>{sub}</div></div>")


def main():
    meta = jload("training_data_meta.json") or {}
    val = jload("ctgan_validation.json") or {}
    finding = jload("audit_finding.json")
    pv = jload("persona_validation.json")

    # KPI strip
    kpis = []
    kpis.append(metric("Real workers trained on", f"{meta.get('n_rows', 0):,}", "IHDS-II microdata"))
    kpis.append(metric("Synthetic workers", f"{val.get('n_synth', 0):,}", "generated by CTGAN"))
    if val:
        kpis.append(metric("Mean KS (continuous)", val.get("mean_ks_stat", "-"), "lower = closer to real"))
        kpis.append(metric("Mean TVD (categorical)", val.get("mean_tvd", "-"), "lower = closer to real"))
        kpis.append(metric("Memorised rows", f"{val.get('privacy', {}).get('exact_duplicate_rate', '-')}", "exact copies (want ~0)"))
    if finding:
        eng = finding["mean_recall_by_language"]["English"]
        low = finding["mean_recall_by_language"][finding["lowest_language"]]
        kpis.append(metric("English vs " + finding["lowest_language"],
                           f"{eng:.2f} → {low:.2f}", "AI welfare-advice recall"))

    # finding table
    finding_tbl = ""
    if finding:
        rows = ""
        for lang in finding["languages"]:
            r = finding["mean_recall_by_language"][lang]
            c = int(finding["mean_answer_chars_by_language"][lang])
            bar = int(r * 100)
            hot = "#2c7fb8" if lang == "English" else "#de2d26"
            rows += (f"<tr><td>{lang}</td>"
                     f"<td><div class='bar'><div style='width:{bar}%;background:{hot}'></div></div> {r:.2f}</td>"
                     f"<td>{c}</td></tr>")
        finding_tbl = (f"<table class='t'><tr><th>Query language</th>"
                       f"<th>Mean welfare-scheme recall</th><th>Answer chars</th></tr>{rows}</table>")

    # sample workers table from CSV
    sample_html = ""
    sp = os.path.join(RESULTS, "synthetic_population_imputed.csv")
    if os.path.exists(sp):
        df = pd.read_csv(sp)
        cols = ["state", "sex", "age", "social_group", "education", "employment_type",
                "annual_wage_inr", "language", "ai_usability_score", "wage_below_minimum"]
        s = df.sample(8, random_state=2)[cols]
        s["annual_wage_inr"] = s["annual_wage_inr"].map(lambda v: f"₹{v:,}")
        head = "".join(f"<th>{c}</th>" for c in cols)
        body = "".join("<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>"
                       for row in s.values)
        sample_html = f"<table class='t small'><tr>{head}</tr>{body}</table>"

    persona_html = ""
    if pv:
        persona_html = (
            f"<p>Two independent imputation methods agree: AI-usability scores from "
            f"structural priors (Layer 2) and from LLM-persona reasoning (Layer 3) "
            f"match within ±1 for <b>{pv['ai_usability_agreement_within_1']:.0%}</b> of "
            f"workers (correlation {pv.get('ai_usability_correlation')}); "
            f"rights-awareness mean abs error {pv['rights_awareness_mae']}.</p>")

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>JANASANKHYA — built</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:#1b2733;background:#f4f6f9}}
 header{{background:linear-gradient(135deg,#034e7b,#2b8cbe);color:#fff;padding:34px 40px}}
 header h1{{margin:0;font-size:30px;letter-spacing:.3px}}
 header p{{margin:8px 0 0;opacity:.92;max-width:880px;line-height:1.5}}
 .wrap{{max-width:1040px;margin:0 auto;padding:26px 20px}}
 section{{background:#fff;border-radius:12px;padding:22px 26px;margin:18px 0;box-shadow:0 1px 4px rgba(0,0,0,.07)}}
 h2{{margin:0 0 6px;color:#034e7b;font-size:21px}}
 .lead{{color:#5a6b7b;margin:0 0 16px}}
 .kpis{{display:flex;flex-wrap:wrap;gap:14px}}
 .metric{{flex:1;min-width:150px;background:#eef4f9;border-radius:10px;padding:14px 16px;text-align:center}}
 .mv{{font-size:24px;font-weight:700;color:#034e7b}}
 .ml{{font-size:13px;margin-top:4px}}
 .ms{{font-size:11px;color:#7d8b99;margin-top:2px}}
 table.t{{border-collapse:collapse;width:100%;margin-top:10px;font-size:14px}}
 table.t.small{{font-size:11.5px}}
 table.t th{{background:#034e7b;color:#fff;padding:8px;text-align:left}}
 table.t td{{padding:7px 8px;border-bottom:1px solid #eee}}
 .bar{{display:inline-block;width:160px;height:12px;background:#e6edf3;border-radius:6px;vertical-align:middle;overflow:hidden}}
 .bar>div{{height:100%}}
 .tag{{display:inline-block;background:#fff7bc;border:1px solid #e3d97a;border-radius:5px;padding:2px 8px;font-size:12px;color:#6b5d00;margin-left:8px}}
 footer{{color:#7d8b99;font-size:12px;padding:20px 40px;line-height:1.6}}
 code{{background:#eef2f6;padding:1px 5px;border-radius:4px;font-size:12.5px}}
</style></head><body>
<header>
 <h1>JANASANKHYA <span style="font-weight:300">· built</span></h1>
 <p>A synthetic population of India's informal workers, generated by a real CTGAN trained on
 IHDS-II microdata, enriched with cited structural priors and LLM-persona reasoning, and used
 to audit whether AI systems give worse welfare advice in low-resource languages.</p>
</header>
<div class="wrap">

 <section>
  <h2>At a glance</h2>
  <div class="kpis">{''.join(kpis)}</div>
 </section>

 <section>
  <h2>The architecture <span class="tag">every variable traces to real data or a citation</span></h2>
  <p class="lead">Four layers turn a real survey into an AI-fairness instrument.</p>
  {img('fig_architecture.png')}
 </section>

 <section>
  <h2>Layer 1 — the CTGAN is real, and it validates</h2>
  <p class="lead">Synthetic distributions are statistically close to the real IHDS-II data,
  and the model does not memorise individuals.</p>
  {img('fig_l1_validation.png')}
 </section>

 <section>
  <h2>It preserves structural inequality, not just averages</h2>
  <p class="lead">The caste and gender wage gaps in the real data survive generation —
  this is what makes the population useful for fairness work.</p>
  {img('fig_structure.png')}
 </section>

 <section>
  <h2>Eight synthetic workers</h2>
  <p class="lead">None is a real person; each is a statistically realistic informal worker
  with imputed AI-interaction variables.</p>
  {sample_html}
 </section>

 <section>
  <h2>The finding — AI welfare advice degrades by language</h2>
  <p class="lead">Same synthetic worker, same welfare question, only the language changes.
  Recall = of the schemes the worker is actually entitled to, how many did the AI surface.</p>
  {img('fig_finding.png')}
  {finding_tbl}
 </section>

 <section>
  <h2>Layers 2 + 3 — convergent validity</h2>
  {persona_html or '<p class="lead">[run Layer 3 to populate]</p>'}
 </section>

</div>
<footer>
 Data: IHDS-II individual file (ICPSR 36151, DS0001). Model: CTGAN (Xu et al., NeurIPS 2019),
 trained {val.get('epochs','?')} epochs on {meta.get('n_rows',0):,} real informal workers.
 AI audit run against the local <code>claude</code> model. Structural priors from Jan Sahas (2020),
 ILO India Employment Report (2024), NITI Aayog (2022), GSMA (2024) — figures editable and to be
 pinned to primary sources during validation. Generated by the JANASANKHYA pipeline.
</footer>
</body></html>"""

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(html)
    print(f"Wrote dashboard -> {OUT}")


if __name__ == "__main__":
    main()
